# Dockerfile
FROM node:18.15.0

# Set working directory
WORKDIR /app

# Copy package.json and package-lock.json
COPY package*.json ./

# Install dependencies
RUN npm install

# Copy all other source files
COPY . .

EXPOSE 3000

# Start the app
CMD ["npm", "run", "dev"]
