version: "3"

services:
  backend:
    build:
      context: .
      dockerfile: server/Dockerfile-backend
    ports:
      - "3001:3001"
    environment:
      - PORT=3001
    volumes:
      - .:/app
      - /app/node_modules

  frontend:
    build:
      context: .
      dockerfile: Dockerfile-frontend
    ports:
      - "5173:5173"
    depends_on:
      - backend
    volumes:
      - .:/app
      - /app/node_modules
